#!/usr/bin/env python

# this is derived/cloned/only-barely-modified from this:
# https://github.com/mozilla-services/syncclient/issues/30

import getpass
import sys
import math
import json
import hmac
import hashlib
import base64
import logging

from Crypto.Cipher import AES
from Crypto import Random
from syncclient.client import SyncClient, FxAClient, TOKENSERVER_URL, six, hexlify, sha256

def main():

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-u', '--user', dest='user', action='store', default=None, help='...')
    opt_parser.add_option('-i', '--interactive', dest='interactive', action='store_true', default=True, help='...')    

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
     
    options, args = opt_parser.parse_args()

    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    user = options.user
    pswd = None

    if options.interactive:
        pswd = getpass.getpass()
    else:
        raise Exception, "this only works in interactive mode"
    
    # Login to FxA and get the keys.
    
    fxaSession = FxAClient().login(user, pswd, keys=True)
    fxaSession.fetch_keys()

    # Connect to sync using FxA browserid assertion
    
    bid_assertion_args = get_browserid_assertion(fxaSession)
    client = SyncClient(*bid_assertion_args)

    # https://github.com/mozilla-services/syncclient/blob/master/syncclient/client.py#L237
    
    collection = "bookmarks"

    """
      {
    "dateAdded": 1537203599742, 
    "title": "Web Authentication API - Web APIs | MDN", 
    "parentName": "Other Bookmarks", 
    "loadInSidebar": false, 
    "bmkUri": "https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#Browser_compatibility", 
    "parentid": "unfiled", 
    "type": "bookmark", 
    "id": "ELOSadMpKvWJ", 
    "tags": [
      "security", 
      "webauthn"
    ]
    },
    """
    
    record = {
        "id": "debug",
        "title": "Mills Field",
        "bmkUri": "https://millsfield.sfomuseum.org",
        # "description": "",
        "loadInSidebar": False,
        "tags": ["sfomuseum"],
        # "keyword": "",
        "parentid": "unfiled",
        "parentName": "Other Bookmarks",
        # "predecessorid": "",
        "type": "bookmark"
    }

    """
    This fails with:

    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://sync-***-us-west-2.sync.services.mozilla.com/1.5/108942993/storage/bookmarks/debug

    Because... ???
    """
    
    print client.put_record(collection, record)

def get_browserid_assertion(fxaSession, tokenserver_url=TOKENSERVER_URL):
    bid_assertion = fxaSession.get_identity_assertion(tokenserver_url)
    _, keyB = fxaSession.keys
    if isinstance(keyB, six.text_type):  # pragma: no cover
        keyB = keyB.encode('utf-8')
    return bid_assertion, hexlify(sha256(keyB).digest()[0:16])
    
if __name__ == '__main__':
    main()
